### ISSUE TITLE
Report initialization

### ISSUE THREAD

**Issue by tripercy** [tripercy/pka-web-dev-final#21]

**Comment by SkyjackerFWO** [comment]
https://docs.google.com/document/d/1JlfkNfgSrZFfUwQcCODdqi18I2gUqs4Fs3nQwMQQlNQ/edit?fbclid=IwZXh0bgNhZW0CMTAAAR39pzkiro--yv3hbdN12EE-1sdhf0rA6Nje7-RcoJiPuKuUfg4elBoiC2w_aem_ZmFrZWR1bW15MTZieXRlcw
